apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: default
spec:
  secretName: my-certificate-secret-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: example.domain
  dnsNames:
  - example.domain
  - '*.example.domain'