apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: nginx-test
spec:
  type: NodePort
  selector:
    app: nginx-test
  ports:
    - port: 8080
      nodePort: 30005
      targetPort: 80
